### ISSUE TITLE
Decidir stack principal a ser utilizada

### ISSUE THREAD

**Issue by marchingbeagle** [marchingbeagle/pipeline-edd#10]
Ideia inicial de stack: ![Imagem do WhatsApp de 2024-11-13 à(s) 22 05 02_a1ad3044](https://github.com/user-attachments/assets/64c19cc4-d3a9-40fe-9ef6-dfbba99e239a)

Após decisao final fazer inserção das informações no README e no MKDOCS.

**Comment by gabrieldorodrigues** [comment]
Como decidido #18 as Stack principais já foram definidas.
